# Generated by Django 3.0.5 on 2021-01-06 04:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('multiplex', '0017_auto_20201016_2100'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pic/StaffProfilePic/')),
                ('address', models.CharField(max_length=40)),
                ('mobile', models.CharField(max_length=20)),
                ('status', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='producer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tempmovie',
            name='distributor',
        ),
        migrations.RemoveField(
            model_name='tempmovie',
            name='producer',
        ),
        migrations.RemoveField(
            model_name='tempmovie',
            name='theatre',
        ),
        migrations.RemoveField(
            model_name='theatre',
            name='user',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='theatre',
        ),
        migrations.DeleteModel(
            name='Distributor',
        ),
        migrations.DeleteModel(
            name='Producer',
        ),
        migrations.DeleteModel(
            name='TempMovie',
        ),
        migrations.DeleteModel(
            name='Theatre',
        ),
    ]
