# Generated by Django 3.0.2 on 2021-01-16 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multiplex', '0018_auto_20210106_0936'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
