# Generated by Django 3.0.2 on 2021-01-16 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multiplex', '0019_delete_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
    ]
