# Generated by Django 3.0.2 on 2021-01-16 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiplex', '0020_remove_customer_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='limitation',
            field=models.CharField(choices=[('Older Kids (7+)', 'Older Kids (7+)'), ('Teens (13+)', 'Teens (13+)'), ('Young Adults (16+)', 'Young Adults (16+)'), ('Adults (18+)', 'Adults (18+)')], default='Older Kids (7+)', max_length=30),
        ),
    ]
