# Generated by Django 3.0.2 on 2021-01-18 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiplex', '0022_auto_20210118_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.CharField(default='General', max_length=200),
        ),
    ]
