# Generated by Django 3.0.2 on 2021-01-18 20:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiplex', '0023_auto_20210118_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='limitation',
            field=models.CharField(choices=[('Older_Kids', 'Older Kids (7+)'), ('Teens', 'Teens (13+)'), ('Young_Adults', 'Young Adults (16+)'), ('Adults', 'Adults (18+)')], default='Older Kids (7+)', max_length=30),
        ),
        migrations.AlterField(
            model_name='movie',
            name='out_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
