# Generated by Django 3.0.2 on 2021-01-19 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiplex', '0024_auto_20210118_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.CharField(choices=[('Action', 'action'), ('Comedy', 'comedy'), ('Drama', 'drama'), ('Fantasy', 'fantasy'), ('Horror', 'horror'), ('Mystery', 'mystery'), ('Romance', 'romance')], default='General', max_length=200),
        ),
    ]
