# Generated by Django 3.0.2 on 2021-01-20 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiplex', '0026_movie_hall'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='org_price',
            field=models.IntegerField(default=200),
        ),
    ]
