# Generated by Django 3.0.2 on 2021-01-20 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiplex', '0027_movie_org_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='popularity',
            field=models.IntegerField(default=0),
        ),
    ]
