# Generated by Django 3.0.2 on 2021-01-21 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiplex', '0029_movie_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='org_price',
            field=models.IntegerField(default=models.IntegerField(default=100)),
        ),
    ]
