# Generated by Django 3.1.7 on 2021-12-31 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multiplex', '0031_remove_movie_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='actor',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='category',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='director',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='popularity',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='video',
        ),
    ]
