# Generated by Django 3.1.7 on 2021-12-31 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multiplex', '0032_auto_20211231_0814'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movie',
            new_name='Coffee',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='movie',
            new_name='multiplex',
        ),
        migrations.RenameField(
            model_name='seat',
            old_name='movie',
            new_name='multiplex',
        ),
    ]
